/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package chapter.create.and.destroy.objects;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public Library(){

    }
}
